
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: entsoe_api_loop
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      # Persist cache and raw data
      - entsoe_cache:/app/cache
      - entsoe_data:/data
    env_file:
      - .env

  run_loop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: entsoe_run_loop
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - entsoe_cache:/app/cache
      - entsoe_data:/data
    env_file:
      - .env
    command: >
      sh -c "python -u ha_entsoe.py run-loop
             --zone ${ZONE_EIC}
             --from ${EXCH_FROM_EIC}
             --to ${EXCH_TO_EIC}
             --tick ${TICK_SECONDS}
             --prices-ttl ${TTL_PRICES}
             --load-da-ttl ${TTL_LOAD_DA}
             --load-act-ttl ${TTL_LOAD_ACT}
             --gen-ttl ${TTL_GEN}
             --netpos-ttl ${TTL_NETPOS}
             --exch-ttl ${TTL_EXCH}"

volumes:
  entsoe_cache:
  entsoe_data: