services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: entsoe_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # Development: uncomment to live-mount source (read-only)
      - ./:/app:ro
      - entsoe_cache:/app/cache
      - entsoe_data:/data
    env_file:
      - .env


volumes:
  entsoe_cache:
  entsoe_data: